### ISSUE TITLE
Only reports results for given stories

### ISSUE THREAD

**Issue by MichaelRijsdijk** [tapack/allure-jbehave-reporter#1]
When running a story like:

```
Validate my special error messages


Scenario: 001 Special validation one
GivenStories:
givenstories/001_given.story,
givenstories/002_given.story
When I open the special screen
Then the special message should be shown

Scenario: 002 Special validation one
GivenStories:
givenstories/001_given.story,
givenstories/002_given.story
When I open the special screen2
Then the special message2 should be shown
```

The Allure xml's only get filled with the results for the given stories, the other steps are not reported.

**Comment by mdolinin** [comment]
Yes this is a bug. I will fix it. But we need to decide how to show this "GivenStories" in the report.
Because they is present inside Scenario -> Allure Test Case, i suggest to map them as nested steps.
Maybe you have better ideas?

**Comment by MichaelRijsdijk** [comment]
I think mapping them as nested steps is correct when looking at the Allure structure.
